<div class="row">
    <div class="col">
        <h1><i class="bi bi-list-task"></i> Liste des tâches</h1>
    </div>
    <div class="col">
        <a href="add_todo.php" class="btn btn-success float-end"><i class="bi bi-plus-square"></i> Add todo</a>
    </div>
</div>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col"><i class="bi bi-check2-square"></i></th>
            <th scope="col">Title</th>
            <th scope="col">Operations</th>
        </tr>
    </thead>
    <tbody>
        <?php if (empty($todos)) : ?>
            <tr>
                <td colspan="3" class="text-center">You have not todos yet!</td>
            </tr>
        <?php else : ?>
            <?php foreach ($todos as $todo) : ?>
                <tr>
                    <th><input type="checkbox" <?= $todo['complete'] ? 'checked' : '' ?>></th>
                    <td class="<?= $todo['complete'] ? 'text-decoration-line-through' : '' ?>"><?= $todo['title'] ?></td>
                    <td>
                        <a href="todo_details.php?id=<?= $todo['id'] ?>" class="btn btn-primary"><i class="bi bi-info-circle"></i></a>
                        <a href="edit_todo.php?id=<?= $todo['id'] ?>" class="btn btn-warning"><i class="bi bi-pencil-square"></i></a>
                        <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteTodo<?= $todo['id'] ?>"><i class="bi bi-trash"></i></button>
                        <!-- Modal -->
                        <div class="modal fade" id="deleteTodo<?= $todo['id'] ?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel"><?= $todo['title'] ?></h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        Do you want to delete this todo ?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <a href="delete_todo.php?id=<?= $todo['id'] ?>" type="button" class="btn btn-danger">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
</table>