<div class="row">
    <div class="col">
        <h3>Add todo <i class="bi bi-plus-square"></i></h3>
    </div>
    <div class="col">
        <a href="./index.php" class="btn btn-primary float-end"><i class="bi bi-house"></i></a>
    </div>
</div>

<form action="<?= $_SERVER['PHP_SELF'] ?>" method="post">
    <div class="mb-3">
        <label for="title" class="form-label">Title</label>
        <input type="text" class="form-control" id="title" name="title">
    </div>
    <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <textarea class="form-control" id="description" name="description"></textarea>
    </div>
    <div class="mb-3">
        <label for="due_date" class="form-label">Due date</label>
        <input type="date" class="form-control" id="due_date" name="due_date">
    </div>
    <button type="submit" class="btn btn-primary"><i class="bi bi-send-plus"></i> Submit</button>
    <button type="reset" class="btn btn-secondary"><i class="bi bi-x-square"></i> Cancel</button>
</form>