
<h1><i class="bi bi-list-task"></i> Liste des tâches</h1>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col"><i class="bi bi-check2-square"></i></th>
            <th scope="col">Title</th>
            <th scope="col">Operations</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($todos as $todo) : ?>
            <tr>
                <th><input type="checkbox" <?= $todo['complete'] ? 'checked' : '' ?>></th>
                <td class="<?= $todo['complete'] ? 'text-decoration-line-through' : '' ?>"><?= $todo['title'] ?></td>
                <td>
                    <a href="todo_details.php?id=<?= $todo['id'] ?>" class="btn btn-primary"><i class="bi bi-info-circle"></i></a>
                    <button class="btn btn-warning"><i class="bi bi-pencil-square"></i></button>
                    <button class="btn btn-danger"><i class="bi bi-trash"></i></button>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
