<link rel="stylesheet" href="./assets/css/signin.css">
<?php if (count($errors) > 0) : ?>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        Wrong credentials!
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<?php endif; ?>
<main class="form-signin">
    <form action="<?php $_SERVER['PHP_SELF'] ?>" method="post">
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

        <div class="form-floating">
            <input type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Email address</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Password</label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit" name="submit">Sign in</button>
        <p class="mt-5 mb-3 text-muted">&copy; ISET Bizerte-DSI21 - 2021</p>
    </form>
</main>