<div class="row">
    <div class="col">
        <h3>Détails de <?= $todo['title'] ?></h3>
    </div>
    <div class="col">
        <a href="./index.php" class="btn btn-primary float-end"><i class="bi bi-house"></i></a>
    </div>
</div>
<div class="card" style="width: 38rem;">
    <div class="card-body">
        <div class="card-title">
            <p><strong>Titre:</strong></p>
            <h5 class="card-title"><?= $todo['title'] ?></h5>
        </div>
        <hr>
        <div class="card-text">
            <p><strong>Description:</strong></p>
            <p><?= $todo['description'] ?></p>
        </div>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Status:</strong> <?= $todo['complete'] ? 'Complete' : 'Incomplete'; ?></li>
        <li class="list-group-item"><strong>due date:</strong> <?= date_format(date_create($todo['due_date']), 'D F d Y') ?></li>
    </ul>
    <div class="card-body">
        <button class="btn btn-warning"><i class="bi bi-pencil-square"></i></button>
        <button class="btn btn-danger"><i class="bi bi-trash"></i></button>
    </div>
</div>
