<div class="row">
    <div class="col">
        <h3>Détails de <?= $todo['title'] ?></h3>
    </div>
    <div class="col">
        <a href="./index.php" class="btn btn-primary float-end"><i class="bi bi-house"></i></a>
    </div>
</div>
<div class="card" style="width: 38rem;">
    <div class="card-body">
        <div class="card-title">
            <p><strong>Titre:</strong></p>
            <h5 class="card-title"><?= $todo['title'] ?></h5>
        </div>
        <hr>
        <div class="card-text">
            <p><strong>Description:</strong></p>
            <p><?= $todo['description'] ?></p>
        </div>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Status:</strong> <?= $todo['complete'] ? 'Complete' : 'Incomplete'; ?></li>
        <li class="list-group-item"><strong>due date:</strong> <?= date_format(date_create($todo['due_date']), 'D F d Y') ?></li>
    </ul>
    <div class="card-body">
        <a href="edit_todo.php?id=<?= $todo['id'] ?>" class="btn btn-warning"><i class="bi bi-pencil-square"></i></a>
        <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteTodo<?= $todo['id'] ?>"><i class="bi bi-trash"></i></button>
        <!-- Modal -->
        <div class="modal fade" id="deleteTodo<?= $todo['id'] ?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel"><?= $todo['title'] ?></h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Do you want to delete this todo ?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <a href="delete_todo.php?id=<?= $todo['id'] ?>" type="button" class="btn btn-danger">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>